version: '3.7'

services:
  backend:
    build:
      context: ./backend
      target: 'develop-stage'
    environment:
      - RUST_BACKTRACE=1
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    command: /bin/sh -c "cargo watch -x run"

volumes:
  cargo-cache:
  target-cache:
