version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: 'develop-stage'
    environment:
      - RUST_BACKTRACE=1
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app/backend
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
<<<<<<< HEAD
    command: /bin/sh -c "cargo watch -i 'log/' -x run"
=======
    command: /bin/sh -c "cargo watch -x 'run --bin rustknock-backend'"
>>>>>>> origin/main

volumes:
  cargo-cache:
  target-cache:
