name: Linux Container Node Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login
      uses: azure/docker-login@v1
      with:
        login-server: helloactix.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Build
      env:
        DOCKER_BUILDKIT: 1
      run: |
        docker build ./backend -t helloactix.azurecr.io/helloactix:${{ github.sha }} -f "backend/Dockerfile"
        docker push helloactix.azurecr.io/helloactix:${{ github.sha }}
    - name: Deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'helloactix'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'helloactix.azurecr.io/helloactix:${{ github.sha }}'